import type { Metadata } from "next";
import "./globals.css";

import { Montserrat } from "next/font/google";
import { PropsWithChildren } from "react";

import Provider from "@/components/Provider";
import { cn } from "@/lib/utils";

const font = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props extends PropsWithChildren {}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={cn("container", font.className)}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
